import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({
  variable: "--font-primary",
  subsets: ["latin"],
  display: "optional",
});

export const metadata = {
  title: "Dompa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.variable}>
      <body className="font-[var(--font-primary)] antialiased">{children}</body>
    </html>
  );
}
